// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7yROTJJnFrMb8Xwm_u-xUwcZm-6ic4Is',
    appId: '1:181435664094:web:76183b33a783c0de6c644f',
    messagingSenderId: '181435664094',
    projectId: 'fluttersample-48129',
    authDomain: 'fluttersample-48129.firebaseapp.com',
    storageBucket: 'fluttersample-48129.appspot.com',
    measurementId: 'G-JY8Y5111S5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAktvjf1oEM5s65ft2mq1bfoAFW6st-F34',
    appId: '1:181435664094:android:0ecb9f11673910c16c644f',
    messagingSenderId: '181435664094',
    projectId: 'fluttersample-48129',
    storageBucket: 'fluttersample-48129.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDs-fze6MS_MZ_87evyyaIvE5C0rrsn13E',
    appId: '1:181435664094:ios:0407da1491ebcc1c6c644f',
    messagingSenderId: '181435664094',
    projectId: 'fluttersample-48129',
    storageBucket: 'fluttersample-48129.appspot.com',
    iosBundleId: 'com.example.firebaseSample',
  );
}
